name: deny

on:
  workflow_call:
    inputs:
      rust-toolchain:
        description: "Rust toolchain; same syntax as dtolnay/rust-toolchain"
        default: "nightly"
        required: false
        type: "string"
      deny-flags:
        description: "Additional flags passed to `cargo deny check`"
        default: "--all-features"
        required: false
        type: "string"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-deny:
    name: cargo deny check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: tempoxyz/gh-actions/vendor/dtolnay/rust-toolchain@6f436eb3a168279692739e8c0c9fdb52b94bfae7
        with:
          toolchain: ${{ inputs.rust-toolchain }}
      - uses: tempoxyz/gh-actions/vendor/EmbarkStudios/cargo-deny-action@6f436eb3a168279692739e8c0c9fdb52b94bfae7
        with:
          command: check all
          arguments: ${{ inputs.deny-flags }}
