name: Dependency Scan

on:
  pull_request:

permissions: {}

jobs:
  dependency-scan:
    uses: tempoxyz/gh-actions/.github/workflows/dependency-scan.yml@a8467566cf2204e895d40f6baf19435c8bc7f921 # 2026-09-28T07-41-23Z-a8467566
    permissions:
      contents: read
      id-token: write
